name: C++ CI with GTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./TaskSchedulerTests

      - name: Lint the project
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --inconclusive --error-exitcode=1 .
