name: Lint C++ Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-tidy

      - name: Run clang-tidy
        run: |
          mkdir build
          cd build
          cmake ..
          clang-tidy ../*.cpp -- -std=c++17
