name: Lint C++ Code

on:
  push:
    paths:
      - '**.cpp'      # Track all C++ source files
      - '**.h'        # Track all header files
  pull_request:
    paths:
      - '**.cpp'      # Track all C++ source files for pull requests
      - '**.h'        # Track all header files for pull requests

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Find all cpp files and run clang-tidy
        run: |
          find src -name "*.cpp" | xargs clang-tidy --extra-arg=-I./include -- -std=c++17
